/* NextBestDollar browser beta. All calculations and saved data run locally. */
const STORAGE_KEY = "nextbestdollar-browser-beta-v1";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const wholeMoney = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

const defaultState = () => ({
  profile: { name: "", age: 25, retirementAge: 65 },
  income: 0,
  expenses: { Housing: 0, Food: 0, Transportation: 0, Utilities: 0, Insurance: 0, Other: 0 },
  cash: 0,
  debts: [],
  goals: [],
  allocation: { cash: 0, debt: 0, brokerage: 0 },
  feedback: []
});

let state = loadState();
function loadState() { try { return { ...defaultState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}") }; } catch { return defaultState(); } }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function number(value) { const parsed = Number(value); return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; }
function monthlyExpenses() { return Object.values(state.expenses).reduce((sum, value) => sum + number(value), 0); }
function monthlyMinimums() { return state.debts.reduce((sum, debt) => sum + number(debt.minimum), 0); }
function debtTotal() { return state.debts.reduce((sum, debt) => sum + number(debt.balance), 0); }
function freeCash() { return state.income - monthlyExpenses() - monthlyMinimums(); }
function format(value) { return money.format(Number(value) || 0); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }

function setPage(page) {
  document.querySelectorAll(".page").forEach(element => element.classList.toggle("active", element.id === `page-${page}`));
  document.querySelectorAll(".nav-link").forEach(element => element.classList.toggle("active", element.dataset.page === page));
  document.querySelector(".sidebar").classList.remove("open");
  window.scrollTo({ top: 0, behavior: "instant" });
  renderPage(page);
}
function renderPage(page) { ({ overview: renderOverview, setup: renderSetup, goals: renderGoals, allocation: renderAllocation, forecast: renderForecast, guide: renderGuide, feedback: renderFeedback })[page](); }
function statCard(label, value, note = "") { return `<article class="card"><p class="metric-label">${label}</p><strong class="metric-value">${value}</strong>${note ? `<p class="small" style="margin-top:.75rem">${note}</p>` : ""}</article>`; }

function renderOverview() {
  const free = freeCash(); const expenses = monthlyExpenses(); const minimums = monthlyMinimums();
  const max = Math.max(state.income, expenses, minimums, 1);
  const bars = [["Take-home income", state.income], ["Living expenses", expenses], ["Debt minimums", minimums]].map(([label, value]) => `<div class="bar-row"><span>${label}</span><div class="bar-track"><div class="bar" style="width:${Math.max(1, value / max * 100)}%"></div></div><span class="bar-value">${format(value)}</span></div>`).join("");
  document.querySelector("#page-overview").innerHTML = `
    <p class="eyebrow">Your plan</p><h1>See your money clearly.</h1><p class="lead">Your monthly picture is built from the amounts you enter. It stays on this device unless you download a backup.</p>
    <div class="card-grid section">${statCard("Monthly breathing room", format(free), "After living expenses and debt minimums")}${statCard("Total debt", format(debtTotal()), `${state.debts.length} account${state.debts.length === 1 ? "" : "s"} recorded`) }${statCard("Cash on hand", format(state.cash), "Available cash you entered")}</div>
    ${free < 0 ? `<div class="callout danger">Your recorded essentials are ${format(Math.abs(free))} above monthly income. Start by reviewing income, living expenses, or debt minimums before setting new targets.</div>` : `<div class="callout">You have ${format(free)} available each month after recorded living expenses and debt minimums. Use My allocation to give it a job.</div>`}
    <div class="two-col section"><article class="card"><h2>Your monthly picture</h2><div class="bar-chart">${bars}</div><p class="small" style="margin-top:1rem">A snapshot of the plan you entered, not a transaction history.</p></article><article class="card"><h2>Next step</h2><p class="lead">${state.goals.length ? "Keep your goals visible while you decide where each available dollar goes." : "Add a goal that matters to you, then test what your monthly plan could do."}</p><div class="button-row"><button class="button" data-go="goals">${state.goals.length ? "View goals" : "Add a goal"}</button><button class="button secondary-button" data-go="allocation">Open allocation</button></div></article></div>
    <p class="footer-note">NextBestDollar is an educational planning tool. It does not provide individualized financial, tax, legal, or investment advice.</p>`;
  bindGoButtons();
}

function renderSetup() {
  const expenseInputs = Object.entries(state.expenses).map(([name, value]) => `<label>${name}<input data-expense="${name}" inputmode="decimal" type="number" min="0" step="1" value="${number(value)}"></label>`).join("");
  const debtRows = state.debts.map((debt, index) => `<tr><td><input data-debt="${index}" data-key="name" value="${escapeHtml(debt.name)}" aria-label="Debt name"></td><td><input data-debt="${index}" data-key="balance" type="number" min="0" value="${number(debt.balance)}" aria-label="Balance"></td><td><input data-debt="${index}" data-key="apr" type="number" min="0" step=".01" value="${number(debt.apr)}" aria-label="APR"></td><td><input data-debt="${index}" data-key="minimum" type="number" min="0" value="${number(debt.minimum)}" aria-label="Minimum"></td><td><button class="icon-button" data-remove-debt="${index}" aria-label="Remove debt">Remove</button></td></tr>`).join("");
  document.querySelector("#page-setup").innerHTML = `
    <p class="eyebrow">Your foundation</p><h1>Build your financial picture.</h1><p class="lead">Enter rounded monthly amounts if you prefer. Everything is saved only in this browser.</p>
    <form id="setup-form" class="section"><article class="card"><div class="field-grid"><label>First name <input id="profile-name" value="${escapeHtml(state.profile.name)}" autocomplete="given-name"></label><label>Current age <input id="profile-age" type="number" min="16" max="100" value="${number(state.profile.age)}"></label><label>Monthly take-home income <input id="monthly-income" inputmode="decimal" type="number" min="0" step="1" value="${number(state.income)}"></label><label>Cash on hand <input id="cash-on-hand" inputmode="decimal" type="number" min="0" step="1" value="${number(state.cash)}"></label></div></article>
      <article class="card form-section"><h2>Monthly living expenses</h2><div class="field-grid">${expenseInputs}</div></article>
      <article class="card form-section"><h2>Loans and debt</h2><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Balance</th><th>APR %</th><th>Monthly minimum</th><th></th></tr></thead><tbody>${debtRows || `<tr><td colspan="5" class="empty">No debt accounts added yet.</td></tr>`}</tbody></table></div><div class="button-row"><button type="button" class="button secondary-button" id="add-debt">Add debt</button></div></article>
      <div class="button-row"><button class="button" type="submit">Save financial picture</button><button class="button secondary-button" type="button" id="restore-button">Restore backup</button></div><p class="status" id="setup-status" aria-live="polite"></p></form>`;
  document.querySelector("#setup-form").addEventListener("submit", event => { event.preventDefault(); state.profile.name = document.querySelector("#profile-name").value.trim(); state.profile.age = number(document.querySelector("#profile-age").value); state.income = number(document.querySelector("#monthly-income").value); state.cash = number(document.querySelector("#cash-on-hand").value); document.querySelectorAll("[data-expense]").forEach(input => state.expenses[input.dataset.expense] = number(input.value)); document.querySelectorAll("[data-debt]").forEach(input => state.debts[number(input.dataset.debt)][input.dataset.key] = input.dataset.key === "name" ? input.value.trim() : number(input.value)); saveState(); document.querySelector("#setup-status").textContent = "Saved on this device."; renderOverview(); });
  document.querySelector("#add-debt").addEventListener("click", () => {
    // Preserve amounts already typed into the form before adding another row.
    state.profile.name = document.querySelector("#profile-name").value.trim();
    state.profile.age = number(document.querySelector("#profile-age").value);
    state.income = number(document.querySelector("#monthly-income").value);
    state.cash = number(document.querySelector("#cash-on-hand").value);
    document.querySelectorAll("[data-expense]").forEach(input => state.expenses[input.dataset.expense] = number(input.value));
    document.querySelectorAll("[data-debt]").forEach(input => state.debts[number(input.dataset.debt)][input.dataset.key] = input.dataset.key === "name" ? input.value.trim() : number(input.value));
    state.debts.push({ name: "Debt", balance: 0, apr: 0, minimum: 0 });
    renderSetup();
  });
  document.querySelectorAll("[data-remove-debt]").forEach(button => button.addEventListener("click", () => { state.debts.splice(number(button.dataset.removeDebt), 1); renderSetup(); }));
  document.querySelector("#restore-button").addEventListener("click", () => document.querySelector("#restore-input").click());
}

function renderGoals() {
  const rows = state.goals.map((goal, index) => { const percent = goal.target ? Math.min(100, goal.current / goal.target * 100) : 0; return `<article class="card goal-card"><div><h3>${escapeHtml(goal.name)}</h3><p class="small">${format(goal.current)} of ${format(goal.target)}</p><div class="progress"><span style="width:${percent}%"></span></div></div><button class="icon-button" data-remove-goal="${index}">Remove</button></article>`; }).join("");
  document.querySelector("#page-goals").innerHTML = `<p class="eyebrow">Your goals</p><h1>Build toward what matters.</h1><p class="lead">Goals connect today’s monthly choices to a future you can see.</p><div class="section">${rows || `<p class="empty">Start with one milestone that matters to you.</p>`}</div><form id="goal-form" class="card section"><h2>Add a goal</h2><div class="field-grid"><label>Goal name <input id="goal-name" required placeholder="Emergency reserve"></label><label>Target amount <input id="goal-target" required type="number" min="1" step="1" placeholder="15000"></label><label>Current amount <input id="goal-current" type="number" min="0" step="1" value="0"></label></div><div class="button-row"><button class="button">Add goal</button></div></form>`;
  document.querySelector("#goal-form").addEventListener("submit", event => { event.preventDefault(); state.goals.push({ name: document.querySelector("#goal-name").value.trim(), target: number(document.querySelector("#goal-target").value), current: number(document.querySelector("#goal-current").value) }); saveState(); renderGoals(); renderOverview(); });
  document.querySelectorAll("[data-remove-goal]").forEach(button => button.addEventListener("click", () => { state.goals.splice(number(button.dataset.removeGoal), 1); saveState(); renderGoals(); renderOverview(); }));
}

function debtProjection(payment) { const debts = state.debts.map(debt => ({ ...debt, balance: number(debt.balance), apr: number(debt.apr), minimum: number(debt.minimum) })); let months = 0; let interest = 0; while (debts.some(debt => debt.balance > .01) && months < 1200) { let extra = Math.max(0, payment - debts.reduce((sum, debt) => sum + debt.minimum, 0)); debts.forEach(debt => { const monthlyInterest = debt.balance * debt.apr / 100 / 12; debt.balance += monthlyInterest; interest += monthlyInterest; }); debts.sort((a,b) => b.apr - a.apr).forEach(debt => { const due = Math.min(debt.balance, debt.minimum + extra); const extraUsed = Math.max(0, due - debt.minimum); debt.balance = Math.max(0, debt.balance - due); extra = Math.max(0, extra - extraUsed); }); months++; } return { months, interest }; }
function brokerageValue(contribution, age) { const years = Math.max(0, age - number(state.profile.age)); const monthlyRate = Math.pow(1.10, 1/12) - 1; const months = years * 12; return contribution * ((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate); }
function renderAllocation() {
  const available = Math.max(0, freeCash()); const alloc = state.allocation; const total = number(alloc.cash) + number(alloc.debt) + number(alloc.brokerage); const reserveTarget = monthlyExpenses() * 6; const cashMonths = alloc.cash > 0 ? Math.max(0, Math.ceil((reserveTarget - state.cash) / alloc.cash)) : null; const payoff = debtTotal() ? debtProjection(monthlyMinimums() + number(alloc.debt)) : null; const retirementValue = brokerageValue(number(alloc.brokerage), number(state.profile.retirementAge));
  const slider = (key, label) => `<div class="slider-row"><div class="slider-top"><span>${label}</span><span>${format(alloc[key])}/month</span></div><input class="allocation-slider" data-allocation="${key}" type="range" min="0" max="${Math.max(available, total, 1)}" step="25" value="${number(alloc[key])}"></div>`;
  document.querySelector("#page-allocation").innerHTML = `<p class="eyebrow">My allocation</p><h1>Give each available dollar a job.</h1><p class="lead">Set the amounts you want to direct each month. The results update on this device as you move the sliders.</p><div class="card section"><p class="metric-label">Monthly cash flow after living expenses and debt minimums</p><strong class="metric-value">${format(freeCash())}</strong>${available ? `<div class="callout">You have ${format(available)} available each month to divide. You can adjust the plan below.</div>` : `<div class="callout danger">There is no available monthly cash flow yet. Update your financial picture before creating new allocation targets.</div>`}${slider("cash", "Cash savings")}${slider("debt", "Extra debt payoff")}${slider("brokerage", "Brokerage investing")}<div class="allocation-total"><span>Allocated</span><span>${format(total)} of ${format(available)}</span></div>${total > available ? `<p class="small" style="color:#a3433d">Your targets exceed available cash by ${format(total - available)}. Reduce one or more sliders.</p>` : `<p class="small">${format(available - total)} remains unassigned each month.</p>`}</div><div class="card-grid section">${statCard("Debt-free estimate", payoff ? (payoff.months >= 1200 ? "More than 100 years" : `${payoff.months} months`) : "No debt recorded", payoff ? `Estimated interest: ${format(payoff.interest)}` : "")}${statCard("Six-month reserve", cashMonths === null ? "Choose a cash amount" : cashMonths <= 0 ? "Funded" : `${cashMonths} months`, `${format(state.cash)} today → ${format(reserveTarget)} target`)}${statCard(`Brokerage at age ${state.profile.retirementAge}`, format(retirementValue), `${format(alloc.brokerage)}/month · 10% long-term S&P 500 planning assumption`)}</div><p class="footer-note">Debt payoff assumes fixed APRs, required minimums, no new borrowing, and extra money paid to the highest-APR debt. Investment growth is an illustration, not a promise.</p>`;
  document.querySelectorAll(".allocation-slider").forEach(sliderElement => sliderElement.addEventListener("input", () => { state.allocation[sliderElement.dataset.allocation] = number(sliderElement.value); saveState(); renderAllocation(); }));
}

function makeChart(values, years) { const width = 760, height = 330, pad = { l: 75, r: 24, t: 24, b: 45 }, max = Math.max(...values.map(item => item.balance), ...values.map(item => item.contributions), 1); const point = (value, i) => `${pad.l + (width - pad.l - pad.r) * i / years},${height - pad.b - (height - pad.t - pad.b) * value / max}`; const balance = values.map((row, i) => point(row.balance, i)).join(" "); const contributions = values.map((row, i) => point(row.contributions, i)).join(" "); const grid = [0,.25,.5,.75,1].map(ratio => { const y = height - pad.b - (height - pad.t - pad.b) * ratio; return `<line x1="${pad.l}" x2="${width-pad.r}" y1="${y}" y2="${y}" stroke="#d6e1dd"/><text x="${pad.l-10}" y="${y+4}" text-anchor="end" fill="#6d817c" font-size="12">${wholeMoney.format(max * ratio)}</text>`; }).join(""); return `<svg class="line-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Investment forecast chart">${grid}<polyline fill="none" stroke="#79a9e8" stroke-width="4" points="${contributions}"/><polyline fill="none" stroke="#16745f" stroke-width="4" points="${balance}"/><text x="${width/2}" y="${height-10}" text-anchor="middle" fill="#6d817c" font-size="12">Years</text></svg>`; }
function renderForecast() {
  const age = number(state.profile.retirementAge); const contribution = number(state.allocation.brokerage); const years = Math.max(1, age - number(state.profile.age)); const annualRate = .10; let balance = 0, contributions = 0; const points = Array.from({ length: years + 1 }, (_, year) => { if (year) { for (let month = 0; month < 12; month++) { balance *= 1 + Math.pow(1 + annualRate, 1/12) - 1; balance += contribution; contributions += contribution; } } return { balance, contributions }; });
  document.querySelector("#page-forecast").innerHTML = `<p class="eyebrow">Forecast</p><h1>See the next move and the longer view.</h1><p class="lead">This browser-only forecast uses a 10% long-term S&P 500 planning assumption. It is a scenario, not a prediction.</p><div class="card section"><div class="field-grid"><label>Current age <input id="forecast-age" type="number" min="16" max="100" value="${number(state.profile.age)}"></label><label>Forecast age <input id="forecast-retirement-age" type="number" min="17" max="100" value="${age}"></label><label>Monthly brokerage contribution <input id="forecast-contribution" type="number" min="0" step="25" value="${contribution}"></label></div><div class="button-row"><button id="update-forecast" class="button">Update forecast</button></div></div><article class="card section"><h2>Brokerage growth illustration</h2>${makeChart(points, years)}<div class="legend"><span>Balance</span><span>Contributions</span></div><div class="card-grid" style="margin-top:1.4rem">${statCard("Illustrative ending balance", format(points.at(-1).balance))}${statCard("Your contributions", format(points.at(-1).contributions))}${statCard("Years modeled", years)}</div></article><p class="footer-note">This estimate excludes taxes, fees, inflation, withdrawals, and changing contribution limits. Markets vary and can lose value.</p>`;
  document.querySelector("#update-forecast").addEventListener("click", () => { state.profile.age = number(document.querySelector("#forecast-age").value); state.profile.retirementAge = number(document.querySelector("#forecast-retirement-age").value); state.allocation.brokerage = number(document.querySelector("#forecast-contribution").value); saveState(); renderForecast(); });
}

function renderGuide() { document.querySelector("#page-guide").innerHTML = `<p class="eyebrow">About this app</p><h1>How NextBestDollar works.</h1><p class="lead">A browser-only planning tool that helps people understand the tradeoffs behind everyday money decisions.</p><div class="card section"><h2>Why this beta is different</h2><p class="lead">Your inputs, calculations, and browser save stay on your device. NextBestDollar does not create an account, connect to a bank, or run a profile database.</p></div><div class="card section"><h2>What each area does</h2><div class="section"><h3>Financial picture</h3><p class="small">Enter monthly income, costs, cash, and debt details.</p></div><div class="section"><h3>Goals</h3><p class="small">Track milestones such as a reserve, home, travel, or debt payoff.</p></div><div class="section"><h3>My allocation</h3><p class="small">Test how available cash could be divided among savings, extra debt payments, and brokerage investing.</p></div><div class="section"><h3>Forecast</h3><p class="small">See a long-term brokerage-growth illustration using a 10% S&P 500 planning assumption.</p></div></div><div class="callout warning section">Download a backup if you want to keep your plan. Clearing browser data can remove locally saved information.</div>`; }
function renderFeedback() { document.querySelector("#page-feedback").innerHTML = `<p class="eyebrow">Beta feedback</p><h1>Help shape NextBestDollar.</h1><p class="lead">Tell us what was useful, confusing, or missing. This feedback is saved on your device until you download it.</p><form id="feedback-form" class="card section"><label>How was the experience?<select id="feedback-rating"><option>Great</option><option>Good</option><option>Okay</option><option>Confusing</option></select></label><label style="margin-top:1rem">What should we improve?<textarea id="feedback-comment" required placeholder="Your feedback"></textarea></label><div class="button-row"><button class="button">Save feedback on this device</button><button type="button" class="button secondary-button" id="download-feedback">Download feedback</button></div><p class="status" id="feedback-status" aria-live="polite"></p></form>`; document.querySelector("#feedback-form").addEventListener("submit", event => { event.preventDefault(); state.feedback.push({ rating: document.querySelector("#feedback-rating").value, comment: document.querySelector("#feedback-comment").value.trim(), createdAt: new Date().toISOString() }); saveState(); document.querySelector("#feedback-comment").value = ""; document.querySelector("#feedback-status").textContent = "Feedback saved on this device."; }); document.querySelector("#download-feedback").addEventListener("click", () => download({ app: "NextBestDollar", feedback: state.feedback }, "nextbestdollar-feedback.json")); }
function download(payload, name) { const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); }
function bindGoButtons() { document.querySelectorAll("[data-go]").forEach(button => button.addEventListener("click", () => setPage(button.dataset.go))); }
document.querySelectorAll(".nav-link").forEach(button => button.addEventListener("click", () => setPage(button.dataset.page)));
document.querySelector(".brand").addEventListener("click", event => { event.preventDefault(); setPage("overview"); });
document.querySelector(".mobile-menu").addEventListener("click", () => document.querySelector(".sidebar").classList.toggle("open"));
document.querySelector("#backup-button").addEventListener("click", () => download(state, "nextbestdollar-private-backup.json"));
document.querySelector("#restore-input").addEventListener("change", event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { state = { ...defaultState(), ...JSON.parse(reader.result) }; saveState(); setPage("setup"); alert("Your backup was restored on this device."); } catch { alert("That file could not be restored."); } }; reader.readAsText(file); });
setPage("overview");
